#!/bin/sh
#
# iconv script to convert encoding from UTF-8 to ASCII-8BIT.
#
# Syntax:
#
#     iconv-from-utf-8-to-ascii-8bit [inputfile ...]
#
# The `iconv` command does character set conversion.
#
# ## About
#
#   * Command: iconv-from-utf-8-to-ascii-8bit
#   * Version: 1.0.0
#   * Created: 2013-01-16
#   * Updated: 2015-01-25
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
iconv -f UTF-8 -t ASCII-8BIT "$@"
